training:
  num_envs: 2
  n_episodes: 500
  episode_length: 500
  learning_rate: 0.02
  noise: 0.03
  directions: 0.5
  curi_learn: 0
  eval_ep: 3
  state_dim: 16
  action_dim: 1

logging:
  api_key: Wlh5wstMNYkxV0yWRxN7JXZRu
  project_name: snake-rl
  log_online: 1
  log_offline: 1
  print_stats: 1
  log_path: log
  tags: toy-1

scene:
  n_envs: 1
  es: 1
  gui: 0
  cam:
    cam_pos: [1.2, 0, 1.2]
    look_at: [0.5, 0, 1]
  gym:
    dt: 0.01
    substeps: 2
    up_axis: z
    type: physx
    physx:
      num_threads: 0
      solver_type: 0 # 0: pgs, 1: tgs
      num_position_iterations: 10
      num_velocity_iterations: 6
      contact_offset: 0.001 # m
      rest_offset: 0.001 # m
      bounce_threshold_velocity: 0.2 # m/s
      max_depenetration_velocity: 5.0 # m/s
      use_gpu: False # Use GPU for physics computation
      always_use_articulations: False #

snake:
  attractor_props:
    stiffness: 1e3
    damping: 2.5e2
  asset_options:
    fix_base_link: False
    flip_visual_attachments: False
    armature: 0.01
    max_linear_velocity: 100.0
    max_angular_velocity: 40.0
    disable_gravity: False
  attractor_props:
    stiffness: 1e3
    damping: 2e2
  shape_props:
    thickness: 1e-1
  dof_props:
    stiffness: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
    damping: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    effort: [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

table:
  dims:
    sx: 10
    sy: 10
    sz: 0.1
  shape_props:
    friction: 0.1
    rolling_friction: 0.1
    torsion_friction: 0.1
    thickness: 2e-3
  asset_options:
    fix_base_link: True
